### ISSUE TITLE
etf/write.go:200: new(big.Int).SetUint64 undefined

### ISSUE THREAD

**Issue by mediocregopher** [goerlang/etf#3]
When I do `go get github.com/goerlang/etf` I get the following:

```
# github.com/goerlang/etf
/usr/lib/go/src/pkg/github.com/goerlang/etf/write.go:200: new(big.Int).SetUint64 undefined (type *big.Int has no field or method SetUint64)
```

Looking at the source for big.Int it looks like there is indeed no function called SetUint64. Did something change somewhere down the line? My version of go is 1.0.3.

**Comment by ftrvxmtrx** [comment]
SetUint64 appeared after 1.0.3, hence the error.
See http://code.google.com/p/go/source/detail?r=954a79ee3ea8

**Comment by Zert** [comment]
Invalid
